registry:
  server: "registry.pivotal.io"
  username: "TANZU-NET-USER"
  password: "TANZU-NET-PASSWORD"
server:
  # Set this service_type to "NodePort" for local clusters like minikube.
  service_type: "LoadBalancer"
  watched_namespace: "default"
  engine_invocation_url: "http://acc-engine.accelerator-system.svc.cluster.local/invocations"
engine:
  service_type: "ClusterIP"